### ISSUE TITLE
Change of namespaces: code not updated 100%

### ISSUE THREAD

**Issue by TBoonX** [dalicc/dalicc#7]
The protocol of multiple namespaces was changed with the last update on this repository, but not all code was updated accordingly.

http://dalicc.net/ns, http://dalicc.net/licenselibrary/, http://dalicc.net/dependencygraph/dg_default are effected.

reasoner/app/plugins/plugins.py line 94 was not updated.

Readme.md at line 46 and 54 was not updated.

getdepgraph.lp was not updated.

**Comment by havurgiray** [comment]
The protocols of the namespaces are changed as https.
